### ISSUE TITLE
adaptor 'transformer' not found in registry

### ISSUE THREAD

**Issue by juggernauts** [compose/transporter#184]
I'm unable to solve this issue on Ubuntu 14.04. 
My config.yaml is
`nodes: 
  localmongo: 
    type: mongodb 
    uri: mongodb://127.0.0.1/client_text 
    debug: true 
  es: 
    type: elasticsearch 
    uri: http://127.0.0.1:9200/ 
  timeseries: 
    type: influx 
    uri: influxdb://root:root@localhost:8086/compose 
  debug: 
    type: file 
    uri: stdout:// 
  foofile: 
    type: file 
    uri: file:///tmp/foo 
  estransformer: 
    type: transformer 
    file: test/transformers/mongo_fields.js `
my application.js is
`Source({name:"localmongo", namespace:"client_text.news_data"})
.transform({name:"estransformer",filename: "transformers/mongo_fields.js"})
.save({name:"es", namespace:"client_text.news_data"});
~                                                      `
However as I test my config by transporter test --config ./test/config.yaml test/application.js, I keep getting the adaptor 'transformer' not found in registry error.

I did a transporter about and I can see the transformer adaptor present.
>> transporter about
transformer          an adaptor that transforms documents using a javascript function
elasticsearch        an elasticsearch sink adaptor
file                 an adaptor that reads / writes files
mongodb              a mongodb adaptor that functions as both a source and a sink
rethinkdb            a rethinkdb adaptor that functions as both a source and a sink

Not sure what am I missing

**Comment by juggernauts** [comment]
Closing this issue as we currently need to add namespace in all the nodes including transformer.

**Comment by matzischatzi** [comment]
I'm using Ubuntu 14.04, elasticsearch 2.3.2, MongoDB 3.2.6, go 1.6.2 and Transporter 0.1.1
I have added the namespace in all the nodes like this:

Source({name:"localmongo", namespace:"foo.bar"}).transform({filename: "transformers/addFullName.js", namespace:"foo.bar"}).save({name:"es", namespace:"foo.bar"});

Now, however, I get the following error message:

transporter: ERROR: transformer error (TypeError
    at <unknown>
    at <unknown>
)
transporter: ERROR: transformer error (TypeError
    at <unknown>
    at <unknown>
)

Does anyone know what I am missing here?

**Comment by matzischatzi** [comment]
Having had a look at the elasticsearch console, I found the following error messages, does anyone know why?   

[2016-05-24 10:54:34,028][DEBUG][action.bulk              ] [Fontanelle] [foo][2] failed to execute bulk item (index) index {[foo][bar][5744078110db117d5e468c37], source[{"_id":"5744078110db117d5e468c37","firstName":"Robert","lastName":"Baratheon"}]}
MapperParsingException[Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters.]
	at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:204)
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:122)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:309)
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:580)
	at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:559)
	at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(TransportIndexAction.java:212)
	at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:224)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:326)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:119)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:68)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:639)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:271)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by vlopez** [comment]
Any progress on this? Still failing
