### ISSUE TITLE
[v0.1.2-beta] panic: open stdout://: is a directory

### ISSUE THREAD

**Issue by Starefossen** [compose/transporter#190]
**Transport version:**

```
v0.1.2-beta+4c8bb7d
```

**config.yml:**

```yaml
nodes:                     
    a:                  
        type: mongo        
        uri: ${MONGODBPROD}
        tail: true         
        debug: true        
    b:                 
        type: file         
        uri: stdout://     
```

**application.js:**

```js
Source({name:"a", namespace: "a.foo"})               
  .save({name:"b", namespace: "b.foo"})           
```

**Command output:**

```
$ transporter run --config config.yml application.js

sync_1  | Mongo Config {URI:mongodb://***:***@*** Namespace:a.foo Ssl:<nil> Timeout: Debug:true Tail:true
 Wc:0 FSync:false Bulk:false}
sync_1  | setting start timestamp: 6281657349941755904
sync_1  | panic: open stdout://: is a directory
sync_1  | 
sync_1  | goroutine 49 [running]:
sync_1  | panic(0xa67a00, 0xc8203a2c60)
sync_1  |       /Users/andrew/gosrc/src/runtime/panic.go:481 +0x3e6
sync_1  | github.com/compose/transporter/pkg/message/adaptor/file.Adaptor.MustUseFile(0x
0, 0x0, 0x0, 0xc82056f1a6, 0x9, 0x0, 0x0)
sync_1  |       /Users/andrew/go/src/github.com/compose/transporter/pkg/message/adaptor/
file/file.go:85 +0xbe
sync_1  | github.com/compose/transporter/pkg/adaptor/file.(*File).dumpMessage(0xc8205176
20, 0x7f8fbf931510, 0xc8203a2c00, 0x0, 0x0, 0x0, 0x0)
sync_1  |       /Users/andrew/go/src/github.com/compose/transporter/pkg/adaptor/file/fil
e.go:122 +0xda
sync_1  | github.com/compose/transporter/pkg/adaptor/file.(*File).(github.com/compose/tr
ansporter/pkg/adaptor/file.dumpMessage)-fm(0x7f8fbf931510, 0xc8203a2c00, 0x0, 0x0, 0x0, 
0x0)
sync_1  |       /Users/andrew/go/src/github.com/compose/transporter/pkg/adaptor/file/fil
e.go:85 +0x50
sync_1  | github.com/compose/transporter/pkg/pipe.(*Pipe).Listen(0xc820377a00, 0xc820520
de0, 0xc82013c320, 0x0, 0x0)
sync_1  |       /Users/andrew/go/src/github.com/compose/transporter/pkg/pipe/pipe.go:106
 +0x252
sync_1  | github.com/compose/transporter/pkg/adaptor/file.(*File).Listen(0xc820517620, 0
x0, 0x0)
sync_1  |       /Users/andrew/go/src/github.com/compose/transporter/pkg/adaptor/file/fil
e.go:85 +0x4da
sync_1  | github.com/compose/transporter/pkg/transporter.(*Node).Start(0xc82050faa0, 0x0
, 0x0)
sync_1  |       /Users/andrew/go/src/github.com/compose/transporter/pkg/transporter/node
.go:161 +0x121
sync_1  | github.com/compose/transporter/pkg/transporter.(*Node).Start.func1(0xc82050faa
0)
sync_1  |       /Users/andrew/go/src/github.com/compose/transporter/pkg/transporter/node
.go:153 +0x21
sync_1  | created by github.com/compose/transporter/pkg/transporter.(*Node).Start
sync_1  |       /Users/andrew/go/src/github.com/compose/transporter/pkg/transporter/node
.go:154 +0x8b
```

**Comment by trinchan** [comment]
resolved in https://github.com/compose/transporter/commit/fc2073a0f9287905376b36ce587bc954a2d32cd0
