### ISSUE TITLE
noop message causes panic

### ISSUE THREAD

**Issue by jipperinbham** [compose/transporter#260]
## Bug report

If a document is skipped via a transform function, the Op type becomes "noop" internally which causes a problem for the Elasticsearch adaptor. Originally reported [here](https://github.com/compose/transporter/pull/95#issuecomment-277715308) by @mpnovikova

config.yaml
```yaml
nodes:  
  sourcemongo:
    type: mongodb
    uri: mongodb://USER:PWD@HOST:PORT/BedrockDocs
    namespace: BedrockDocs.normaldocs
    debug: true
  destes:
    type: elasticsearch
    uri: http://USER:PWD@HOST:PORT
    namespace: ops.normaldocs
    debug: true
```
app.js
```javascript
var pipeline = Source({name:"sourcemongo"})
  .transform({filename: "transformers/normaldoc.js", namespace: "BedrockDocs.normaldocs"})
  .save({name:"destes"}) 
```
transformer.js
```javascript
module.exports = function(msg) {
  console.log("transformer: " + JSON.stringify(msg))
  if (msg.data['type'] != 'Company') { 
    return false; 
  }
  return msg;
}
```

### System info:

- Transporter version
0.1.2
- OS
any
- DB version(s)
MongoDB and Elasticsearch

### Reproducible Steps:

run transporter

### What did you expect to happened?

only a subset of documents should be sent to elasticsearch from mongodb

### What actually happened?

transporter panicked and crashed

```
transporter run --config normaldocs.yaml normaldocs.js 
INFO[0000] SYNC Processing db1:27017...                 
INFO[0000] Establishing new connection to db1:27017 (timeout=5s)... 
INFO[0000] failed to parse duration, , falling back to default timeout of 30s 
INFO[0000] Connection to db1:27017 established.         
INFO[0000] adaptor Starting...                           path=sourcemongo
INFO[0000] starting Read func                            db=BedrockDocs
INFO[0000] boot map[sourcemongo:mongodb ccbc3c47-c46f-48f5-6027-13791acdf865:transformer destes:elasticsearch]  ts=1486400048134095445
INFO[0000] adaptor Listening...                          path="sourcemongo/ccbc3c47-c46f-48f5-6027-13791acdf865/destes"
INFO[0000] Establishing new connection to db0:27017 (timeout=1h0m0s)... 
INFO[0000] SYNC Adding db1:27017 to cluster as a slave. 
INFO[0000] Connection to db0:27017 established.         
INFO[0000] SYNC Synchronization was complete (got data from primary). 
INFO[0000] SYNC Synchronization completed: 1 master(s) and 1 slave(s) alive. 
INFO[0000] collection count                              db=BedrockDocs num_collections=5
INFO[0000] skipping iteration...                         collection="customer_doc_counts" db=BedrockDocs
INFO[0000] skipping iteration...                         collection=docstats db=BedrockDocs
INFO[0000] skipping iteration...                         collection="ipec_results" db=BedrockDocs
INFO[0000] sending for iteration...                      collection=normaldocs db=BedrockDocs
INFO[0000] skipping iteration...                         collection=system.indexes db=BedrockDocs
INFO[0000] done iterating collections                    db=BedrockDocs
INFO[0000] iterating...                                  collection=normaldocs
INFO[0000] Establishing new connection to db0:27017 (timeout=1h0m0s)... 
INFO[0000] Connection to db0:27017 established.         
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xbec242]

goroutine 47 [running]:
panic(0xe36080, 0xc42000e070)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
github.com/compose/transporter/vendor/gopkg.in/olivere/elastic%2ev5.(*BulkService).estimateSizeInBytes(0xc420082d10, 0x0, 0x0, 0xc4205f6be0)
	/Users/JP/gocode/src/github.com/compose/transporter/vendor/gopkg.in/olivere/elastic.v5/bulk.go:147 +0x22
github.com/compose/transporter/vendor/gopkg.in/olivere/elastic%2ev5.(*BulkService).EstimatedSizeInBytes(0xc420082d10, 0xc420023718)
	/Users/JP/gocode/src/github.com/compose/transporter/vendor/gopkg.in/olivere/elastic.v5/bulk.go:137 +0x9d
github.com/compose/transporter/vendor/gopkg.in/olivere/elastic%2ev5.(*bulkWorker).commitRequired(0xc42026db80, 0xc420023708)
	/Users/JP/gocode/src/github.com/compose/transporter/vendor/gopkg.in/olivere/elastic.v5/bulk_processor.go:539 +0x61
github.com/compose/transporter/vendor/gopkg.in/olivere/elastic%2ev5.(*bulkWorker).work(0xc42026db80)
	/Users/JP/gocode/src/github.com/compose/transporter/vendor/gopkg.in/olivere/elastic.v5/bulk_processor.go:439 +0x1d6
created by github.com/compose/transporter/vendor/gopkg.in/olivere/elastic%2ev5.(*BulkProcessor).Start
	/Users/JP/gocode/src/github.com/compose/transporter/vendor/gopkg.in/olivere/elastic.v5/bulk_processor.go:297 +0x335
```

**Comment by mpnovikova** [comment]
Thank you, appreciate the quick turn around

**Comment by jipperinbham** [comment]
until we can get the fix in, would you mind trying the following:

```javascript
module.exports = function(msg) {
  if (msg.data['type'] != 'Company') { 
    msg.ns = 'DROP'; 
  }
  return msg;
}
```

This _should_ effectively cause any documents to get filtered out via the namespace matching that occurs between each node in the pipeline.

**Comment by jipperinbham** [comment]
@mpnovikova actually, the transformer still needs to abide by the 2 part namespace in 0.1.2, so it'd be:

```javascript
module.exports = function(msg) {
  if (msg.data['type'] != 'Company') { 
    msg.ns = 'DROP.DROP'; 
  }
  return msg;
}
```
