### ISSUE TITLE
Abnormal terminations create a panic in node shutdown

### ISSUE THREAD

**Issue by codepope** [compose/transporter#306]
## Bug report

Almost all abnormal terminations result in a panic.

### System info:

- Transporter version
0.2.1 and later
- OS
macOS
- DB version(s)
N/A

### Reproducible Steps:

Configure a Transporter so that an error occurs during its running - this includes Control-C on a long running transporter.

You will see a shutdown happening like so:

```
^CINFO[0001] adaptor Stopping...                           path="source/dump/sink"
(lots of "file already closed" errors omitted)
INFO[0001] adaptor Listen closing...                     path="source/dump/sink"

panic: close of closed channel

goroutine 1 [running]:
github.com/compose/transporter/adaptor/mongodb.(*MongoDB).Stop(0xc4200f22a0, 0xc4201bd9e0, 0x0)
	/Users/JP/gocode/src/github.com/compose/transporter/adaptor/mongodb/mongodb.go:196 +0x39e
github.com/compose/transporter/pipeline.(*Node).Stop(0xc4201bd200)
	/Users/JP/gocode/src/github.com/compose/transporter/pipeline/node.go:144 +0x38
github.com/compose/transporter/pipeline.(*Node).Stop(0xc4201bd1a0)
	/Users/JP/gocode/src/github.com/compose/transporter/pipeline/node.go:146 +0x67
github.com/compose/transporter/pipeline.(*Node).Stop(0xc4201bd140)
	/Users/JP/gocode/src/github.com/compose/transporter/pipeline/node.go:146 +0x67
github.com/compose/transporter/pipeline.(*Pipeline).Stop(0xc420072300)
	/Users/JP/gocode/src/github.com/compose/transporter/pipeline/pipeline.go:100 +0x4d
main.(*JavascriptBuilder).Run.func2(0x1efaf60, 0xc42042f150)
	/Users/JP/gocode/src/github.com/compose/transporter/cmd/transporter/javascript_builder.go:309 +0x2d
github.com/compose/transporter/vendor/github.com/oklog/oklog/pkg/group.(*Group).Run(0xc420509d88, 0xc420138700, 0x1)
	/Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/oklog/oklog/pkg/group/group.go:64 +0x15b
main.(*JavascriptBuilder).Run(0xc4200f2460, 0x0, 0x0)
	/Users/JP/gocode/src/github.com/compose/transporter/cmd/transporter/javascript_builder.go:321 +0x2e1
main.runRun(0xc4200101a0, 0x1, 0x1, 0x3, 0x0)
	/Users/JP/gocode/src/github.com/compose/transporter/cmd/transporter/run.go:32 +0x2b0
main.main()
	/Users/JP/gocode/src/github.com/compose/transporter/cmd/transporter/main.go:62 +0x105
```

### What did you expect to happened?

Not for the application to panic.

### What actually happened?

It paniced.

There appears to be either more than one call to close each adapter node down or the other end of the channel has already been closed before it gets to this point. 

This could be, therefore, running close(n.done) on the node before running the other two close down routines. When close is called on an already closed channel, Go apps panic (by design apparently).

**Comment by jipperinbham** [comment]
fixed via https://github.com/compose/transporter/commit/feebbd96ab7a11fbbe44ab49421b18bbede93db3

please re-open if still experiencing an issue

**Comment by rossjones** [comment]
This still happens for me (0.3.0/OSX) when running a mongo->mongo pipeline.

The run didn't complete cleanly because of "flush error, E11000 duplicate key error index" followed by "ERROR: write message error (E11000 duplicate key error index...".

It appears to then start a connection to the sink, the iteration is cancelled, appears to clean up and then panics with 

```
goroutine 1 [running]:
github.com/compose/transporter/pipeline.(*Node).stop(0xc4200ee900, 0x0, 0x0)
	/Users/JP/gocode/src/github.com/compose/transporter/pipeline/node.go:269 +0x114
github.com/compose/transporter/pipeline.(*Node).Stop(0xc4200ee900)
	/Users/JP/gocode/src/github.com/compose/transporter/pipeline/node.go:259 +0x2b
github.com/compose/transporter/pipeline.(*Pipeline).Stop(0xc4201d0a80)
	/Users/JP/gocode/src/github.com/compose/transporter/pipeline/pipeline.go:94 +0x4d
main.(*Transporter).Run.func2(0x2152720, 0xc4209b5140)
	/Users/JP/gocode/src/github.com/compose/transporter/cmd/transporter/goja_builder.go:103 +0x2a
github.com/compose/transporter/vendor/github.com/oklog/oklog/pkg/group.(*Group).Run(0xc42003de90, 0xc4201eebc0, 0x1)
	/Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/oklog/oklog/pkg/group/group.go:64 +0x15b
main.(*Transporter).Run(0xc4201c4140, 0xb, 0xc4201c4140)
	/Users/JP/gocode/src/github.com/compose/transporter/cmd/transporter/goja_builder.go:114 +0x2d6
main.runRun(0xc420088060, 0x0, 0x0, 0x3, 0x0)
	/Users/JP/gocode/src/github.com/compose/transporter/cmd/transporter/run.go:21 +0x10a
main.main()
	/Users/JP/gocode/src/github.com/compose/transporter/cmd/transporter/main.go:57 +0x105
```

It it's useful, the last part of the log where the error happens is at https://gist.github.com/rossjones/ef75b8bf84a9a012fd1946747ca933d0

Not sure how much of a big deal it is given the process dies directly afterwards, but I thought it might be worth re-opening....
