### ISSUE TITLE
Mongo to Elastisearch - panic: Panic at 40: connection error

### ISSUE THREAD

**Issue by gustavorps** [compose/transporter#432]
Not able to connect to Elasticsearch on Elastic.co Cloud

### Relevant pipeline.js:
```js
var source = mongodb({
  "uri": "mongodb://user:pass@mongo.server.com:27017/db",
  "timeout": "30s",
  "tail": true
})

var sink = elasticsearch({
  "uri": "https://user@xxxx.europe-west1.gcp.cloud.es.io:9243",
  "timeout": "40s",
  "write_timeout": "30s"
})

t.Source("source", source, "tweets").Save("sink", sink, "/twitter/statuses")
```
### System info:

- Transporter version: quay.io/compose/transporter:v0.5.0
- OS: Linux Lubuntu 16.04
- Mongo version: 3.4
- Elasticsearch version: 5.6.3

### Reproducible Steps:

1. Copy code
2. Set Mongo URI and Elasticsearch URI
3. `docker run --rm -v $(pwd):/workdir -w /workdir quay.io/compose/transporter:v0.5.0 transporter test -log.level "debug" "pipeline.js"`

### What did you expect to happened?
Work or another error than `panic: Panic at 40: connection error`

### What actually happened?
```
> docker run --rm -v $(pwd):/workdir -w /workdir quay.io/compose/transporter:v0.5.0 transporter test -log.level "debug" "pipeline.js"
panic: connection error, https://c7836a67e8f2d42096f7857db08d53c6.europe-west1.gcp.cloud.es.io:9243 [recovered]
	panic: Panic at 40: connection error, https://c7836a67e8f2d42096f7857db08d53c6.europe-west1.gcp.cloud.es.io:9243 [recovered]
	panic: Panic at 40: connection error, https://c7836a67e8f2d42096f7857db08d53c6.europe-west1.gcp.cloud.es.io:9243

goroutine 1 [running]:
github.com/compose/transporter/vendor/github.com/dop251/goja.(*Runtime).RunProgram.func1(0xc42012dd88)
	/Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/dop251/goja/runtime.go:779 +0x98
panic(0xe01c60, 0xc420266b00)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/compose/transporter/vendor/github.com/dop251/goja.(*vm).try.func1(0xc420190750, 0x0, 0xc42012dc60, 0x0, 0x0, 0x0, 0xc42012dcb8)
	/Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/dop251/goja/vm.go:364 +0x32e
panic(0xe4d560, 0xc420266ac0)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
main.(*Node).Save(0xc4201f46e0, 0x15dade0, 0xc4201f4700, 0xc4201c4500, 0x3, 0x4, 0x0, 0x0)
	/Users/JP/gocode/src/github.com/compose/transporter/cmd/transporter/goja_builder.go:264 +0x3b6
reflect.callMethod(0xc4201f66c0, 0xc42012da18)
	/usr/local/Cellar/go/1.8.3/libexec/src/reflect/value.go:640 +0x18a
reflect.methodValueCall(0x15dade0, 0xc4201f4700, 0xc4201c4500, 0x3, 0x4, 0x5, 0x7d6ffd, 0xc420193420, 0x0, 0x38, ...)
	/usr/local/Cellar/go/1.8.3/libexec/src/reflect/asm_amd64.s:29 +0x40
github.com/compose/transporter/vendor/github.com/dop251/goja.(*vm)._nativeCall(0xc420190750, 0xc4201e6dc0, 0x3)
	/Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/dop251/goja/vm.go:1827 +0x2e9
github.com/compose/transporter/vendor/github.com/dop251/goja.call.exec(0xc400000003, 0xc420190750)
	/Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/dop251/goja/vm.go:1808 +0x6ff
github.com/compose/transporter/vendor/github.com/dop251/goja.(*call).exec(0xc4201f2a44, 0xc420190750)
	<autogenerated>:816 +0x55
github.com/compose/transporter/vendor/github.com/dop251/goja.(*vm).run(0xc420190750)
	/Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/dop251/goja/vm.go:288 +0x7f
github.com/compose/transporter/vendor/github.com/dop251/goja.(*vm).(github.com/compose/transporter/vendor/github.com/dop251/goja.run)-fm()
	/Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/dop251/goja/vm.go:375 +0x2a
github.com/compose/transporter/vendor/github.com/dop251/goja.(*vm).try(0xc420190750, 0xc42012dcc0, 0x0)
	/Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/dop251/goja/vm.go:370 +0x119
github.com/compose/transporter/vendor/github.com/dop251/goja.(*vm).runTry(0xc420190750, 0xf86378)
	/Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/dop251/goja/vm.go:375 +0x4f
github.com/compose/transporter/vendor/github.com/dop251/goja.(*Runtime).RunProgram(0xc420196180, 0xc4201c4480, 0x0, 0x0, 0x0, 0x0)
	/Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/dop251/goja/runtime.go:790 +0x210
github.com/compose/transporter/vendor/github.com/dop251/goja.(*Runtime).RunScript(0xc420196180, 0x0, 0x0, 0xc42013a1c0, 0x1bb, 0x1bb, 0x1bb, 0x1bb, 0xc42013a1c0)
	/Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/dop251/goja/runtime.go:769 +0xa8
github.com/compose/transporter/vendor/github.com/dop251/goja.(*Runtime).RunString(0xc420196180, 0xc42013a1c0, 0x1bb, 0x3bb, 0xc42013a1c0, 0x1bb, 0x0)
	/Users/JP/gocode/src/github.com/compose/transporter/vendor/github.com/dop251/goja/runtime.go:758 +0x51
main.newBuilder(0x7ffeb6af9f5f, 0x1a, 0x3, 0x3, 0x0)
	/Users/JP/gocode/src/github.com/compose/transporter/cmd/transporter/goja_builder.go:52 +0x354
main.runTest(0xc420074020, 0x3, 0x3, 0x4, 0x0)
	/Users/JP/gocode/src/github.com/compose/transporter/cmd/transporter/test.go:20 +0xed
main.main()
	/Users/JP/gocode/src/github.com/compose/transporter/cmd/transporter/main.go:63 +0x105
```

**Comment by zoheb391** [comment]
Had a similar issue. Elastic image includes xpack security by default  and the solution was to disable it via env variables. 

`environment: [
        'xpack.security.enabled=false',
    ]`

**Comment by jipperinbham** [comment]
I don't know what the `xpack.security.enabled` implies but ideally we'd like transporter to be able to support xpack as I know it's a feature most users have and want. @zoheb391 any help on the details here?

**Comment by georgehao** [comment]
the same issue, how to resolve?

**Comment by pranaygp** [comment]
It seems like this issue was related to missing `ca-certificates` in an older version of the docker image. It's fixed in the latest docker image.

In my case (where I use the docker image as a previous step in a multi step docker build, and copy the built binary) I needed to add a `RUN apk --no-cache add ca-certificates` to the final docker image before transporter worked correctly
