### ISSUE TITLE
Elasticsearch bulk insertion error

### ISSUE THREAD

**Issue by lvidarte** [compose/transporter#81]
I can't get transporter to work with mongo. What I'm missing? Thanks.

My env

    ubuntu 14.04
    transporter 0.0.3
    mongodb 2.6.10
    elasticsearch 1.5.2

My mongo collection

    > use boom
    switched to db boom
    > db.foo.find()
    { "_id" : ObjectId("558463dc13c7ddef81f3bc76"), "name" : "bar" }

My config

    nodes:
      mongodb:
        type: mongo
        uri: mongodb://localhost/boom
        namespace: boom.foo
        tail: true
        debug: true
      es:
        type: elasticsearch
        uri: http://localhost:9200/boom
        namespace: boom.foo

My app

    pipeline = Source({name:"mongodb"}).save({name:"es"})

Run transporter

    $ transporter run --config config.yaml app.js
    Mongo Config {URI:mongodb://localhost/boom Namespace:boom.foo Debug:true Tail:true Wc:0 FSync:false Bulk:false}
    setting start timestamp: 6162164565128773632

After a while

    transporter: CRITICAL: elasticsearch error (Bulk Insertion Error. Failed item count [1])

Elasticsearch error log

    [2015-06-19 16:05:42,468][DEBUG][action.bulk              ] [Perseus] [boom][3] failed to execute bulk item (index) index {[boom][foo][AU4NNllCvshBiB_rZsxF], source[{"_id":"558463dc13c7ddef81f3bc76","name":"bar"}]}
    org.elasticsearch.index.mapper.MapperParsingException: failed to parse [_id]
	    at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:409)
	    at org.elasticsearch.index.mapper.internal.IdFieldMapper.parse(IdFieldMapper.java:295)
	    at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:706)
	    at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:497)
	    at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:544)
	    at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:493)
	    at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:453)
	    at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:432)
	    at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:149)
	    at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:515)
	    at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:422)
	    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	    at java.lang.Thread.run(Thread.java:745)
    Caused by: org.elasticsearch.index.mapper.MapperParsingException: Provided id [AU4NNllCvshBiB_rZsxF] does not match the content one [558463dc13c7ddef81f3bc76]
	    at org.elasticsearch.index.mapper.internal.IdFieldMapper.parseCreateField(IdFieldMapper.java:310)
	    at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:399)
	    ... 13 more

**Comment by lvidarte** [comment]
I added the following transform.js file and now it works

    module.exports = function(doc) {
      doc._id = doc._id['$oid'];
      return doc;
    }

My app

    pipeline = Source({name:"mongodb"}).transform({filename: 'transform.js'}).save({name:"elasticsearch"});

**Comment by sunshineo** [comment]
I had to do
```
module.exports = function(doc) {
  doc.data._id = doc.data._id['$oid'];
  return doc;
}
```
